training:
  num_epochs: 2
  batch_size: 32  
  learning_rate: 0.001
  optimizer: 'SGD' # Adam or SGD
  momentum: 0.9
  num_workers: 0

model:
  edge: 'AlexNet_EDGE'
  server: 'AlexNet_SERVER'
  save_path: 'cifar_net.pth'
  save_model: false

dataset:
  data: 'CIFAR10' # 'CIFAR10' or 'MNIST'
  validation_split: 0.1
  subset_fraction: 1

rabbitmq:
  host: 'rabbitmq'
  port: 5672
  username: 'guest'
  password: 'guest'