training:
  num_epochs: 5
  batch_size: 32  
  learning_rate: 0.001

model:
  name: 'AlexNet'
  save_path: 'cifar_net.pth'
  save_model: false

dataset:
  name: 'CIFAR10' # 'CIFAR10' or 'MNIST'
  validation_split: 0.1
  subset_fraction: 0.001